import { z } from "@hono/zod-openapi";
import { createdAt, updatedAt } from "../common/schema.js";

export const UserSchema = z.object({
  // The unique ID for the user, typically an auto-generated string.
  id: z.uuid().openapi({
    description: "ID of the user, a UUIDv7 generated by the database",
    example: "018f0a5e-8f3a-7b2c-9d4e-1a2b3c4d5e6f",
  }),

  // The user's chosen nickname or username (varchar 32, unique).
  username: z.string().min(1).max(32).openapi({
    description: "The user's unique nickname or username",
    example: "cakra",
  }),

  // The full name of the user (varchar 80).
  fullName: z.string().min(1).max(80).openapi({
    description: "The user's full name",
    example: "Cakra Buana",
  }),

  // The user's email address (varchar 254, unique), validated format.
  email: z.email().max(254).openapi({
    description: "The user's email address",
    example: "cakra.buana@example.com",
  }),

  createdAt,
  updatedAt,
});

export const PrivateUserSchema = UserSchema;

export const PublicUserSchema = UserSchema.omit({
  email: true,
});

export const UsersSchema = z.array(PublicUserSchema);

export const UsersIdSchema = z.object({
  id: z.uuid(),
});

export type PrivateUser = z.infer<typeof PrivateUserSchema>;
